language: node_js
node_js:
  - "13"
services:
    - docker
notifications:
    email:
        if: branch = master
        recipients:
            - franco.liberali@gmail.com
            - ejusto@fi.uba.ar
            - meiglesias@fi.uba.ar
            - lsportelli@fi.uba.ar
install:
    - echo 'No se ejecuta npm porque es una Docker build'
before_script:
    - '$TRAVIS_BUILD_DIR/bin/travis/start-test-server'
script:
    - '$TRAVIS_BUILD_DIR/bin/travis/run-unit-tests'
    - '$TRAVIS_BUILD_DIR/bin/travis/run-acceptance-tests-on-master-or-pr'
after_success:
    - '$TRAVIS_BUILD_DIR/bin/travis/run-coveralls-on-master-or-pr'
after_script:
    - '$TRAVIS_BUILD_DIR/bin/travis/stop-test-server'
deploy:
    provider: script
    script:
        $TRAVIS_BUILD_DIR/bin/travis/deploy-to-heroku
    on:
        branch: master
