language: node_js
node_js:
    - "13"
services:
    - docker
env:
    - RAMA_MASTER=(TRAVIS_BRANCH = 'master')
    - CORRER_TESTS_DE_INTEGRACION=(RAMA_MASTER || TRAVIS_PULL_REQUEST = true)
before_install:
    # login to docker registries (dockerhub)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - git clone https://github.com/FrancoLiberali/behave-test.git
    - sudo pip install --upgrade pip
install:
    # install deps
    - npm install
    - cd behave-test && sudo pip install -r requirements.txt
before_script:
    - 'if [ "$CORRER_TESTS_DE_INTEGRACION" = "true" ]; then docker-compose up -d --build; fi' # levantar la aplicacion
script:
    - npm test # unit tests
    - echo "$(CORRER_TESTS_DE_INTEGRACION)"
    - 'if [ "$CORRER_TESTS_DE_INTEGRACION" = "true" ]; then behave; fi'  # test de integracion
after_script:
    - 'if [ "$CORRER_TESTS_DE_INTEGRACION" = "true" ]; then docker-compose down; fi'
after_success:
    - docker tag app $DOCKER_USERNAME/app:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_USERNAME/app:$TRAVIS_BUILD_NUMBER
    - docker tag app $DOCKER_USERNAME/app:latest
    - docker push $DOCKER_USERNAME/app:latest
