language: node_js
node_js:
    - "13"
services:
    - docker
before_install:
    # login to docker registries (dockerhub)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - git clone https://github.com/FrancoLiberali/behave-test.git
    - sudo pip install --upgrade pip
install:
    # install deps
    - npm install
    - echo "$(pwd)"
    - cd behave-test && sudo pip install -r requirements.txt
before_script:
    - docker-compose up -d --build # levantar la aplicacion
script:
    - npm test # unit tests
    - echo "$(pwd)"
    - behave # test de integracion
after_script:
    - docker-compose down
after_success:
    - docker tag app $DOCKER_USERNAME/app:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_USERNAME/app:$TRAVIS_BUILD_NUMBER
    - docker tag app $DOCKER_USERNAME/app:latest
    - docker push $DOCKER_USERNAME/app:latest
