language: node_js
node_js:
    - "13"
services:
    - docker
before_install:
    # login to docker registries (dockerhub)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - git clone https://github.com/FrancoLiberali/behave-test.git
install:
    # install deps
    - npm install
    - cd behave-test && sudo pip install -r requirements.txt
script:
    - npm test # unit tests
    - docker-compose up # levantar la aplicacion
    - cd behave-test && behave # test de integracion
after_success:
    - docker tag app $DOCKER_USERNAME/app:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_USERNAME/app:$TRAVIS_BUILD_NUMBER
    - docker tag app $DOCKER_USERNAME/app:latest
    - docker push $DOCKER_USERNAME/app:latest
