language: node_js
node_js:
    - "13"
services:
    - docker
before_install:
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "hola"; fi'
    # login to docker registries (dockerhub)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - git clone https://github.com/FrancoLiberali/behave-test.git
    - sudo pip install --upgrade pip
install:
    # install deps
    - npm install
    - cd behave-test && sudo pip install -r requirements.txt
before_script:
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then docker-compose up -d --build; fi' # levantar la aplicacion
script:
    - npm test # unit tests
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then behave; fi'  # test de integracion
after_script:
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then docker-compose down; fi'
after_success:
    - docker tag app $DOCKER_USERNAME/app:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_USERNAME/app:$TRAVIS_BUILD_NUMBER
    - docker tag app $DOCKER_USERNAME/app:latest
    - docker push $DOCKER_USERNAME/app:latest
