language: node_js
node_js:
    - "13"
services:
    - docker
notifications:
    email:
        if: branch = master
        recipients:
            - franco.liberali@gmail.com
            - ejusto@fi.uba.ar
            - meiglesias@fi.uba.ar
before_install:
    # instalar heroku CLI
    - wget -qO- https://toolbelt.heroku.com/install.sh | sh
    # login to heroku registries
    - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
    - git clone https://github.com/FrancoLiberali/behave-test.git
    - sudo pip install --upgrade pip
install:
    # install deps
    - npm install
    - cd behave-test && sudo pip install -r requirements.txt
before_script:
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then docker-compose up -d --build; fi' # levantar la aplicacion
script:
    - npm test # unit tests
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then behave; fi'  # test de integracion
after_script:
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then docker-compose down; fi'
after_success:
    - 'if [ "$TRAVIS_BRANCH" = "master" ]; then
    cd ..;
    npm run coveralls;
    docker build -t app .;
    docker tag app registry.heroku.com/$HEROKU_APP_NAME/web;
    fi'
deploy:
    provider: script
    script:
        # push to heroku
        docker push registry.heroku.com/$HEROKU_APP_NAME/web;
        heroku container:release web --app $HEROKU_APP_NAME
    on:
        branch: master
