version: '3.1'
services:
    chotuve_app:
        build: .
        restart: always
        links:
            - db
        environment:
            DB_HOST: "db"
        ports:
           - 35080:8080
        volumes:
            - ./:/home/node/app
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: app
        volumes:
            - chotuve_app_pg_data:/var/lib/postgresql/data
volumes:
        chotuve_app_pg_data:
