version: '3.1'
services:
    chotuve_app:
        build: .
        restart: always
        links:
            - db
        environment:
            MONGODB_URL: "mongodb://db:27017/hello-node-dev"
            PORT: 8080
        ports:
           - ${HELLO_NODE_PORT:-27080}:8080
    db:
        image: mongo
        restart: always
        volumes:
            - chotuve_app_mongo_data:/data/db
volumes:
        chotuve_app_mongo_data:
